name: Deploy Static Site

on:
  push:
    # This ensures it ONLY runs when you push a tag starting with 'v'
    tags:
      - 'v*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build WASM
        run: |
          ./scripts/build-wasm.sh
          cp wasm_exec.js docs/static/scripts/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build
        run: |
          cd docs
          npm install
          npm run build

      - name: Copy WASM to build
        run: cp chip-8.wasm docs/build/assets/

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
